platform:
  os: linux
  arch: arm64


kind: pipeline
type: docker
name: build

steps:
  - name: build-image
    image: docker:cli
    environment:
      DOCKER_BUILDKIT: 1
    commands:
      - |
        docker build \
          --file dockerfilefast \
          --tag ghcr.io/deep-jiwan/mypackages/traefik-dynamic-editor:latest \
          --tag ghcr.io/deep-jiwan/mypackages/traefik-dynamic-editor:${DRONE_COMMIT_SHA} \
          --tag ghcr.io/deep-jiwan/mypackages/traefik-dynamic-editor:autobuild \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --label org.opencontainers.image.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
          --label org.opencontainers.image.revision=${DRONE_COMMIT_SHA} \
          --label org.opencontainers.image.source=${DRONE_REPO_LINK} \
          --label org.opencontainers.image.url=${DRONE_REPO_LINK} \
          .

  - name: push-image
    image: docker:cli
    environment:
      GHCR_USERNAME:
        from_secret: ghcr_username
      GHCR_TOKEN:
        from_secret: ghcr_token
    commands:
      - echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
      - docker push ghcr.io/deep-jiwan/mypackages/traefik-dynamic-editor:latest
      - docker push ghcr.io/deep-jiwan/mypackages/traefik-dynamic-editor:${DRONE_COMMIT_SHA}
      - docker push ghcr.io/deep-jiwan/mypackages/traefik-dynamic-editor:autobuild
      - docker logout ghcr.io

  - name: redeploy-stack
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USER
      key:
        from_secret: SSH_KEY
      script:
        - echo "Downloading latest stack file..."
        - curl -L -o docker-compose-deploy.yml https://raw.githubusercontent.com/Deep-Jiwan/traefik-dynamic-editor/main/docker-compose-deploy.yml

        - echo "Pulling latest image..."
        - docker compose -f docker-compose-deploy.yml pull

        - echo "Starting temporary container..."
        - docker run -d --name traefik-dynamic-backend-temp ghcr.io/deep-jiwan/mypackages/traefik-dynamic-editor:autobuild

        - echo "Waiting 5s for temporary container..."
        - sleep 5

        - echo "Removing old container..."
        - docker rm -f traefik-dynamic-backend2 || true  

        - echo "Starting main container from compose..."
        - docker compose -f docker-compose-deploy.yml up -d --force-recreate

        - echo "Cleaning temporary container..."
        - docker rm -f traefik-dynamic-backend-temp || true