platform:
  os: linux
  arch: arm64

kind: pipeline
type: docker
name: build

steps:
  - name: build-docker-image
    image: plugins/docker:linux-arm64
    environment:
      TAG_SHA: ${DRONE_COMMIT_SHA:-autobuild}  # fallback if SHA empty
    settings:
      repo: ghcr.io/deep-jiwan/mypackages/traefik-dynamic-editor
      tags:
        - latest
        - autobuild
        - ${TAG_SHA}
      dockerfile: Dockerfile
      registry: ghcr.io
      platforms:
        - linux/arm64
      purge: false
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token

  - name: redeploy-stack
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USER
      key:
        from_secret: SSH_KEY
      script:
        - echo "Downloading latest stack file..."
        - curl -L -o docker-compose-deploy.yml https://raw.githubusercontent.com/Deep-Jiwan/traefik-dynamic-editor/main/docker-compose-deploy.yml
        - echo "Deploying stack..."
        - docker compose -f docker-compose-deploy.yml up -d
