name: traefik-config-editor

services:
  traefik-dynamic-backend:
    platform: linux/arm64
    image: ghcr.io/deep-jiwan/mypackages/traefik-dynamic-editor:autobuild
    container_name: traefik-dynamic-backend
    ports:
      - "8010:8010"
    environment:
      - PORT=8010
      - DYNAMIC_CONFIG_PATH=../dynamic/dynamic.yml
      - TRAEFIK_CONFIG_PATH=../config/traefik.yaml
      - TRAEFIK_DASHBOARD_URL=https://dashboard-deep.adgone.co.tz
    volumes:
      - /var/lib/docker/volumes/traefik/dynamic:/app/dynamic:rw
      - /var/lib/docker/volumes/traefik/config:/app/config:rw
    
    networks:
      - frontend

    labels:
      - sablier.enable=true
      - sablier.group=config-services

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8010/api/health"]
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 5s

networks:
  frontend:
    external: true