name: traefik-config-editor

services:
  traefik-dynamic-backend:
    platform: linux/arm64
    image: ghcr.io/deep-jiwan/mypackages/traefik-dynamic-editor:autobuild
    container_name: traefik-dynamic-backend
    ports:
      - "8010:8010"
    environment:
      - PORT=8010
      - DYNAMIC_CONFIG_PATH=../dynamic/dynamic.yml
      - TRAEFIK_CONFIG_PATH=../config/traefik.yaml
      - TRAEFIK_DASHBOARD_URL=https://dashboard-deep.adgone.co.tz
    volumes:
      - /var/lib/docker/volumes/traefik/dynamic:/app/dynamic:rw
      - /var/lib/docker/volumes/traefik/config:/app/config:rw

    labels:
      - sablier.enable=true
      - sablier.group=config-services
      - io.portainer.stack.endpoint="1"
      - io.portainer.stack.name="traefik-dynamic-backend"
    restart: unless-stopped
